{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.nifiSingleDisk }}
{{- if .Values.persistence.nifiSingleDisk.enabled }}
{{- if .Values.persistence.nifiSingleDisk.existingPV }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nifireg.svcname" . }}--single--pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nifireg.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.nifiSingleDisk.existingPV.accessModes |default "ReadWriteOnce" }}
  storageClassName: "{{ .Values.persistence.nifiSingleDisk.existingPV.storageClass |default "slow" }}"
  resources:
    requests:
      storage: {{ .Values.persistence.nifiSingleDisk.storageSize |default "1Gi" }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
